
name: Release and Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get date
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ env.SHORT_SHA }}
          name: Build ${{ env.SHORT_SHA }}
          body: |
            Docker image built and published:
            - `${{ secrets.DOCKERHUB_USERNAME }}/voltalis-bridge:${{ env.SHORT_SHA }}`
            - `${{ secrets.DOCKERHUB_USERNAME }}/voltalis-bridge:latest`
            Build date: ${{ env.BUILD_DATE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./voltalis-bridge
          file: ./voltalis-bridge/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/voltalis-bridge:${{ env.SHORT_SHA }}
            ${{ secrets.DOCKERHUB_USERNAME }}/voltalis-bridge:latest
